### ISSUE TITLE
Address Auth error

### ISSUE THREAD

**Issue by edavalosanaya** [RedForestAI/RedForest#176]

**Comment by edavalosanaya** [comment]
This is the error in the server:

```bash
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options","reason":{"errorType":"Error","errorMessage":"Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options","stack":["Error: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options","    at Proxy.callable (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:13:12754)","    at T.setCookie (/var/task/.next/server/chunks/7699.js:1:5521)","    at /var/task/.next/server/chunks/7699.js:1:157811","    at Array.forEach (<anonymous>)","    at T.setItem (/var/task/.next/server/chunks/7699.js:1:157794)","    at eV (/var/task/.next/server/chunks/7699.js:1:71506)","    at an._saveSession (/var/task/.next/server/chunks/7699.js:1:109910)","    at an._callRefreshToken (/var/task/.next/server/chunks/7699.js:1:108874)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async an.__loadSession (/var/task/.next/server/chunks/7699.js:1:97703)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options","    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)","    at process.emit (node:events:529:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections **(node:internal/process/task_queues:96:32)"]}**
```


```bash
[97;46m << query [1;97;46m #1 auth.getProfile [0m {
  input: undefined,
  result: c [TRPCClientError]: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options
      at c.from (/var/task/.next/server/chunks/3269.js:1:9298)
      at /var/task/.next/server/app/page.js:263:300594
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    meta: undefined,
    shape: undefined,
    data: undefined,
    [cause]: tF [Error]: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options
        at Proxy.callable (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:13:12754)
        at T.setCookie (/var/task/.next/server/chunks/7699.js:1:5521)
        at /var/task/.next/server/chunks/7699.js:1:157811
        at Array.forEach (<anonymous>)
        at T.setItem (/var/task/.next/server/chunks/7699.js:1:157794)
        at eV (/var/task/.next/server/chunks/7699.js:1:71506)
        at an._saveSession (/var/task/.next/server/chunks/7699.js:1:109910)
        at an._callRefreshToken (/var/task/.next/server/chunks/7699.js:1:108874)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async an.__loadSession (/var/task/.next/server/chunks/7699.js:1:97703)
  },
  elapsedMs: 119
}
```
