### ISSUE TITLE
Gaze heatmap not displaying in report

### ISSUE THREAD

**Issue by edavalosanaya** [RedForestAI/RedForest#230]
```
page-65a5c10eb9a848b5.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'entries')
    at page-65a5c10eb9a848b5.js:1:9588
    at page-65a5c10eb9a848b5.js:1:10089
    at page-65a5c10eb9a848b5.js:1:10205
```

```
!function(e) {
    for (let t in e.perStudentDatas) {
        let a = e.perStudentDatas[t]
          , l = function(e) {
            let t = {}
              , a = e.actions
              , l = {}
              , n = {
                start: new Date,
                end: new Date
            }
              , s = -1;
            for (let[e,r] of a.entries()) // <----- error here
                if (0 != e) {
                    if ("readingStart" == r[1])
                        t.readingStart = r[0];
                    else if ("questionStart" == r[1]) {
                        t.questionStart = r[0];
                        let e = new Date(t.readingStart)
                          , a = new Date(t.questionStart);
                        t.coldreadTime = (a.getTime() - e.getTime()) / 1e3
                    } else if ("pdfLoad" == r[1]) {
                        let e = Number(JSON.parse(r[2]).index);
                        e != s && (-1 != s ? (n.end = new Date(r[0]),
                        s in l ? l[s].push(n) : l[s] = [n],
                        n = {
                            start: new Date(r[0]),
                            end: new Date
                        }) : n.start = new Date(r[0]),
                        s = e)
                    }
                    e == a.length - 1 && (n.end = new Date(r[0]),
                    s in l ? l[s].push(n) : l[s] = [n])
                }
            return t.pdfTimes = l,
            t
        }(a.logs);
        for (let e in l)
            if (l.hasOwnProperty(e)) {
                let t = l[e];
                a.dataStore[e] = t
            }
    }
    e.setPerStudentData(e.perStudentDatas)
}
```

**Comment by edavalosanaya** [comment]
It seems as though a student downloads all other students data

**Comment by edavalosanaya** [comment]
It issue that 1 test student data that isn't complete is processed and obviously is having issues.
